set nocompatible

" vim-plug
if has('nvim')
    call plug#begin('~/.local/share/nvim/plugged')
else
    call plug#begin(expand('$DOTFILES/vim/plugged'))
endif
Plug 'tpope/vim-abolish'
Plug 'mileszs/ack.vim'
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'vadskye/vim-checkpoint'
Plug 'tpope/vim-commentary'
Plug 'vim-scripts/Conque-Shell'
Plug 'coot/CRDispatcher'
Plug 'chrisbra/csv.vim'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'junegunn/vim-easy-align'
" Plug 'mattn/emmet-vim'
" Plug 'vadskye/vim-emotions'
Plug 'coot/EnchantedVim'
" Plug 'Konfekt/Fastfold'
Plug 'dag/vim-fish', {'for': ['fish']}
" Note: You may need to update fzf with `cd ~/.fzf; git pull; ./install`.
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
" Updating binaries takes a weirdly long time
" Plug 'fatih/vim-go', {'branch': 'release', 'do': ':GoUpdateBinaries', 'tag': 'v1.18'}
Plug 'fatih/vim-go', {'branch': 'release', 'tag': 'v1.18'}
Plug 'jparise/vim-graphql', {'for': ['typescript', 'typescript.tsx']}
Plug 'Galooshi/vim-import-js'
Plug 'michaeljsmith/vim-indent-object'
Plug 'pangloss/vim-javascript', {'for': ['javascript', 'javascript.jsx']}
Plug 'mxw/vim-jsx' " for: javascript doesn't work here
Plug 'vim-scripts/L9'
" Plug 'vim-latex/vim-latex', {'for': ['tex', 'latex']}
" Plug 'lervag/vimtex'
Plug 'vadskye/vim-meta'
Plug 'vim-scripts/mru.vim'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'scrooloose/nerdtree'
Plug 'moll/vim-node'
Plug 'jvirtanen/vim-hcl'
Plug 'vim-perl/vim-perl', {'for': 'perl'}
Plug 'vadskye/vim-psql', {'for': 'sql'}
Plug 'digitaltoad/vim-pug', {'for': ['jade', 'pug']}
Plug 'hynek/vim-python-pep8-indent', {'for': 'python'}
Plug 'vim-python/python-syntax', {'for': 'python'}
Plug 'tpope/vim-repeat'
" also install https://github.com/fannheyward/coc-rust-analyzer
" do NOT use https://github.com/neoclide/coc-rls it is slower
Plug 'rust-lang/rust.vim'
" Plug 'justinmk/vim-sneak'
Plug 'ervandew/supertab'
Plug 'keith/swift.vim'
Plug 'tpope/vim-surround'
Plug 'majutsushi/tagbar'
Plug 'tomtom/tlib_vim'
Plug 'leafgarland/typescript-vim', {'for': 'typescript'}
Plug 'SirVer/ultisnips'
" Plug 'Quramy/tsuquyomi', {'for': 'typescript'}
Plug 'Shougo/vimproc', {'do': 'make'}
Plug 'mustache/vim-mustache-handlebars', {'for': 'mustache'}
Plug 'amadeus/vim-mjml', {'for': 'mjml'}
if has('nvim')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
elseif has('lua')
    Plug 'Shougo/neocomplete.vim'
endif
call plug#end()

source $VIMRUNTIME/mswin.vim

function SourceVimrcFile(name, ...)
    if a:0 >= 1
        let l:directory = a:1
    endif
    if a:0 >= 2
        let l:prefix = a:2
    endif

    if ! exists("l:directory")
        if exists("g:vimrc_directory")
            let l:directory = g:vimrc_directory
        elseif has("win32")
            let l:directory = "$HOME/vimfiles"
        elseif has("unix")
            let l:directory = "$HOME/.vim"
        endif
    endif

    let filename = expand(l:directory . "/vimrc_" . a:name)
    try
        exec "source " . filename
    catch
        echo "Sourcing '" . filename . "' failed: " . string(v:exception)
    endtry
endfunction

source $VIMRUNTIME/macros/matchit.vim
call SourceVimrcFile("basic")
call SourceVimrcFile("remappings")
call SourceVimrcFile("appearance")
call SourceVimrcFile("command_management")
call SourceVimrcFile("files")
call SourceVimrcFile("folding")
call SourceVimrcFile("internal")
call SourceVimrcFile("motion")
call SourceVimrcFile("plugins")
call SourceVimrcFile("searching")
call SourceVimrcFile("tags")
call SourceVimrcFile("text")
call SourceVimrcFile("windows_and_buffers")
if has('python') || has('python3')
    call SourceVimrcFile("terminal")
endif
