#!/bin/bash

stty ixany
stty ixoff -ixon
stty stop undef
stty start undef
set completion-ignore-case on

# enable globstar
shopt -s globstar

export PROMPT_COMMAND="history -a; history -r;"
export PS1="$NS_Cyan[\\w$NS_Cyan]\n$NS_Yellow\$$NS_Nocolor "

# enable fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
